server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tAswVLFXthxTnQFQr8j
    keySecret: 47OreiFhEjuEZTRfI7foRypTT7sP9v
    bucketName: srb-file-221111-1